---

# Example task file to combine results of multiple queries under a given
# ansible_fact
#
# - name: run sql command
#     command: psql -U <user> -d <db> -c "<command>"
#   register: query_results

# Idealy you would run this after a query that returns a single row.
# ex:
# query_results = [ { key = value} ]
- name: append "{{query[1]['name']}}" variable to sql_fact dict
  set_fact:
    sql_facts: "{{sql_facts|combine({query[1]['name']: query_results.query_results[0].values()|list|first}, recursive=True)}}"

- name: debug task | sql_facts
  debug: var=sql_facts
  when: db_upgrader_debug
