---

- debug: var=hostvars[engine]
- debug: var=engine
# - debug: var=role_path
# - debug: msg={{ 'srx_' ~  engine ~ '_ui_password'}}
# - fail:

- name: Install psycop2
  pip:
    name: psycopg2

- name: loading sql sql_history from '{{sql_history_logfile}}'
  set_fact:
    sql_history: "{{lookup('file', sql_history_logfile)}}"
  # ignore errors caused by inexisting file, this might be the case on the
  # first run
  ignore_errors: True

# iterate over a previously explicitely defined list of queries or sql scripts
- include: sql_declarative_mode.yml
  when: sql_jobs is defined or sql_con_args is defined

# If role was given a sql_path argument, iterate over all files under that path.
- include: sql_path_mode.yml
  when: sql_path is defined
