---

# Run sql script phoenix

# Requirements:
  #- /usr/lib/phoenix/bin/sqlline.py present on the system

- name: run phoenix query from fileglob
  shell: "/usr/lib/phoenix/bin/sqlline.py {{sql_conn_targets['host']}}:{{sql_conn_targets['port']}} {{item}}"

- include: log_query_to_sql_hist.yml
