---

# Run sql query on postgres database and optionaly register results for later
# use.
#
# This is included by:
#   - postgresql_var_query
#   - postgresql_adm_query

# todo: move this elsewhere
- name: Install psycop2
  pip:
    name: psycopg2

- name: run postgres query | "{{query[1]['query']}}"
  postgresql_query:
    # creds
    login_user: "{{sql_conn_creds['postgres']['user']}}"
    login_password: "{{sql_conn_creds['postgres']['password']}}"
    # target
    login_host: "{{sql_conn_targets['postgres']['host']|default(omit)}}"
    login_unix_socket: "{{sql_conn_target_args['postgres']['unix_socket']|default(omit)}}"
    ssl_mode: "{{sql_conn_targets['postgres']['ssl_mode']|default(omit)}}"
    ssl_rootcert: "{{sql_conn_targets['postgres']['ssl_rootcert']|default(omit)}}"
    # query
    db: "{{query[1]['db']|default(query[0]['db'])}}"
    query: "{{query[1]['query']}}"
    positional_args: "{{query[1]['positional_args']|default(omit)}}"
    named_args: "{{query[1]['named_args']|default(omit)}}"

    # optionaly optionaly turn result into a fact//variable
    fact: "{{query['fact']|default(omit)}}"
  delegate_to: localhost
  run_once: True
  register: query_results

- include: debug_query_task.yml
  when: db_upgrader_debug
