---

# This task necessary because data structure is different when in fileglob mode

# Requirements:
#   - psycopg2

- name: run postgres file query (fileglob iteration)
  postgresql_query:
    # creds
    login_user: "{{sql_conn_creds['user']}}"
    login_password: "{{sql_conn_creds['password']}}"
    # target
    login_host: "{{sql_conn_targets['host']|default(omit)}}"
    login_unix_socket: "{{sql_conn_targets['unix_socket']|default(omit)}}"
    ssl_mode: "{{sql_conn_targets['ssl_mode']|default(omit)}}"
    ssl_rootcert: "{{sql_conn_targets['ssl_rootcert']|default(omit)}}"
    # query
    db: "{{sql_db}}"
    query: "{{item}}"
    autocommit: "{{sql_autocommit}}"

- include: log_query_to_sql_hist.yml
