---

# This task necessary because data structure is different when in fileglob mode

- name: run postgres file query (fileglob iteration)
  postgresql_query:
    # creds
    login_user: "{{sql_conn_creds['user']}}"
    login_password: "{{sql_conn_creds['password']}}"
    # target
    login_host: "{{sql_conn_targets['host']|default(omit)}}"
    login_unix_socket: "{{sql_conn_targets['unix_socket']|default(omit)}}"
    ssl_mode: "{{sql_conn_targets['ssl_mode']|default(omit)}}"
    ssl_rootcert: "{{sql_conn_targets['ssl_rootcert']|default(omit)}}"
    # query
    db: "{{sql_db}}"
    query: "{{item}}"
    # named_args: "{{sql_facts|default(omit)}}"
  delegate_to: localhost
  run_once: True

# log job
- name: log query result to sql '{{sql_history_logfile}}'
  lineinfile:
    create: yes
    line: "{{item}}"
    dest: "{{sql_history_logfile}}"
