---

# Run sql query on postgres database and optionaly register results for later
# use.
#
# This is included by:
#   - postgresql_var_query.yml
#   - postgresql_adm_query.yml

- name: run postgres query | "{{query[1]['query']}}"
  postgresql_query:
    # creds
    login_user: "{{sql_conn_creds['postgres']['user']}}"
    login_password: "{{sql_conn_creds['postgres']['password']}}"
    # target
    login_host: "{{sql_conn_targets['postgres']['host']|default(omit)}}"
    login_unix_socket: "{{sql_conn_target_args['postgres']['unix_socket']|default(omit)}}"
    ssl_mode: "{{sql_conn_targets['postgres']['ssl_mode']|default(omit)}}"
    ssl_rootcert: "{{sql_conn_targets['postgres']['ssl_rootcert']|default(omit)}}"
    # query
    db: "{{query[0]['db']|default(sql_db)}}"
    query: "{{query[1]['query']}}"
    positional_args: "{{query[1]['positional_args']|default(omit)}}"
    named_args: "{{query[1]['named_args']|default(omit)}}"
    autocommit: "{{query[0]['autocommit']|default(sql_autocommit)}}"

    # optionaly optionaly turn result into a fact//variable
    fact: "{{query['fact']|default(omit)}}"
  register: query_results
