---

# First loop over sql_var_queries to gather variables from various databases
- include: "{{query[0]['engine']}}_var_query.yml"
  with_subelements:
     - "{{sql_var_queries|default(omit)}}"
     - queries
  loop_control:
    loop_var: query

# Second loop to run arbitrary sql_adm_queries in a defined sequence
# A query job does the following things
- include: "{{query[0]['engine']}}_adm_query.yml"
  with_subelements:
     - "{{sql_adm_queries|default(omit)}}"
     - queries
  when: "query[1]['query'] not in sql_history"
  loop_control:
    loop_var: query
